### ISSUE TITLE
Zero-copy strings lead to segmentation fault after closing the environment

### ISSUE THREAD

**Issue by lukas-zech-software** [Venemo/node-lmdb#69] opened 2016-06-30 06:12 UTC
I recently ran into an issue where NodeJS reproducible crashed with an **Segmentation fault** error when trying to access data read from an node-lmdb environment.

The scenario was this: Small LMDB environment, 3 test entries **keyIsUint32** was set to **false**, UTF8 string with about 12 characters where used as keys. Data was binary buffer.

The data was read with a cursor using **getCurrentBinary** and was stored in a **Map** using the key returned by the cursor as key and the binary buffer as data.

After the all data was read, the cursor, txn, dbi and environment were properly closed and the Map was returned to the calling code.

However upon accessing the keys of the map (mind not the data, only the key), the node process would quit with a **segmentation fault** error. 
I debugged the node process with [lldb](http://lldb.llvm.org/) and found that there was an illegal attempt to read invalid memory access causing a **EXC_BAD_ACCESS** error.

I then realised that this must be due to V8 the **zero-copy** feature used for string, which means that the string of the key actually resides in the memory used by LMDB and only the reference is passed to the JavaScript. Therefore the reference points to invalid memory once the environment is closed an LMDB frees the memory.

The solution therefore is quite simple: Copying the content of the key to a new memory address by calling `new Buffer(key)` and then make that new Buffer a string again. 
After doing so, the string can safely be accessed.

I have a few questions about this:
1. Is the above conclusion correct and would you suggest another solution?
2. Why does this not affect the binary buffer read from LMDB? The README states that both, **string** and **binary** are provided via **zero-copy**, but accessing the binary buffer does not cause the segmentation fault.

I would greatly appreciate if this was mentioned clearly in the README and/or the examples as this might be very troublesome to debug for most. 
If you want, I'll prepare and PR with updated README me and examples.

PS: This behaviour can easily be reproduced with example **4-cursors.js** by storing the **key** and **value** in the **printFunc** on a new Map and log this Map after `env.close()` was called

**Comment by braydonf** [comment] 2016-06-30 23:04
Good to know, could be good to note that the `env` is expected to be held open for the duration of accessing values and the application?

I've run into an issue when calling `new Buffer(key)` from `getCurrentBinary` (https://github.com/Venemo/node-lmdb/issues/71) I'm curious how it was working in the case above or if you have you seen this behavior.

**Comment by lukas-zech-software** [comment] 2016-07-01 08:53
@braydonf 
Copying the key to a new Buffer worked flawlessly for me, only difference I can see in your implementation is the Encoding. I used **UTF8** while you use **HEX** - although I can't see why this should make any difference.

Which NodeJS version are you using? 
I did my tests on ``v5.7.0``

If you can upgrade your NodeJS, try ``v6.0`` or above and try the new ``Buffer.from`` methode

**Comment by braydonf** [comment] 2016-07-01 11:45
Still saw the issue when using `utf8` encoding. I tried running with `v6.2.0` and there was the same issue using `Buffer.from`.  However there are a bunch of other `C stack traces` with warnings about `v8::ObjectTemplate::Set() with non-primitive values is deprecated`. Also tried node `v5.7.1`, and `v4.4.5`. I've been using `new Buffer(key.slice(0))` to work-around it.

**Comment by braydonf** [comment] 2016-07-02 13:01
FYI: This may be covered in the docs already at: https://github.com/Venemo/node-lmdb#limitations-of-node-lmdb

> Because of the nature of LMDB, the data returned by txn.getString() and txn.getBinary() is only valid until the next put operation or the end of the transaction. If you need to use the data later, you will have to copy it for yourself.

**Comment by braydonf** [comment] 2016-07-02 13:03
This issue I think is also related: https://github.com/Venemo/node-lmdb/issues/49

**Comment by braydonf** [comment] 2016-07-02 13:45
It actually looks like the issue isn't when the transaction is closed, but when the environment is closed. Also it only affects the key and not the value.

```js
it('segment fault', function(done) {
  var expectedKey = '822285ee315d2b04';
  var expectedValue = new Buffer('ec65d632d9168c33350ed31a30848d01e95172931e90984c218ef6b08c1fa90a', 'hex');
  var env = new lmdb.Env();
  env.open({
    path: testDirPath,
    maxDbs: 12,
    mapSize: 16 * 1024 * 1024 * 1024
  });
  var dbi = env.openDbi({
    name: 'testkeys',
    create: true
  });
  var txn = env.beginTxn();
  txn.putBinary(dbi, expectedKey, expectedValue);
  txn.commit();
  var txn2 = env.beginTxn();
  var cursor = new lmdb.Cursor(txn2, dbi);
  var key;
  var value;
  cursor.goToFirst();
  cursor.getCurrentBinary(function(returnKey, returnValue) {
    key = returnKey;
    //key = JSON.parse(JSON.stringify(returnKey)); this will fix the segfault issue                                                                                                                                                                                                           
    value = returnValue;
  });
  cursor.close();
  txn2.abort();
  dbi.close();
  env.close();
  key.should.equal(expectedKey);
  value.compare(expectedValue).should.equal(0);
  done();
});
```

**Comment by Venemo** [comment] 2016-07-03 12:18
Hey guys,

Sorry for chiming in so late; I owe you an explanation. Quoting the LMDB documentation:

> Values returned from the database are valid only until a subsequent update operation, or the end of the transaction. Do not modify or free them, they commonly point into the database itself.

The fact that it works for you that way and they are still valid after you close the transaction but haven't yet closed the environment is mere chance and I wouldn't rely on this behaviour.  
When I started `node-lmdb` my goals were to preserve as much of the speed benefits of lmdb as possible, so I decided to adopt the zero-copy property. Unfortunately, this doesn't map to JavaScript as well as it works in a low-level language like C. I do realize that this makes `node-lmdb` somewhat non-intuitive to use. The reason why `ExternalStringResource` pops up in the debugger is because that is where "the magic" happens (with regards to strings, anyway).

Now you guys aren't the first ones who got bitten by this, so I also realize that I need to come up with something that at least makes the hard realization easier. So far, I've promised to give an API which allows the user to copy strings (without hassling with it in JavaScript), but additionally I've also got several ideas to help:

* Make `ExternalStringResource` track which transaction created it and in case the transaction is already closed, throw an error when the user tries to access the string. This would make string access a little bit slower, but not significantly.
* Make the transaction track the `ExternalStringResource` instances that it created and invalidate their contents when the transaction is closed. This would not affect performance, but would basically silently empty all the strings, which makes it hard to debug if the user is unaware of this behaviour.
* Make the transaction track the `ExternalStringResource` instances that it created and implicitly copy all their contents before the transaction is closed. This might lead to a **lot** of overhead in case of string objects that are still in memory but which the GC hasn't cleaned up yet.

As users, which of the above would make the most sense to you?

**Comment by braydonf** [comment] 2016-07-03 13:36
In response to ideas listed:

1. This could make it more clear that the value is no longer accessible due to the transaction closing, but should be careful how it would affect performance. How would this apply to buffers? I haven't been able to reproduce the issue with buffer values returned.

2. I agree, it would be better to throw an error than to silently fail that could cascade into other bugs that would be difficult to debug.

3. This would most likely cancel the performance benefits, as all values would eventually be copied. Having an API to specify copy behavior I think would be most beneficial, as mentioned in https://github.com/Venemo/node-lmdb/issues/49#issuecomment-190602664.

I think it's a good idea to have an API for copying values, perhaps something such as:

```js
var valueCopy = txn.getBinaryCopy(dbi, 'key');
var zeroCopy = txn.getBinary(dbi, 'key');
```

However, copying would be the exception in the above. Since values are expected to live as long as there is a reference to it, it could be intuitive to have the zero copy value be the exception:

```js
var valueCopy = txn.getBinary(dbi, 'key');
var zeroCopy = txn.getBinaryZeroCopy(dbi, 'key');

// or

var valueCopy = txn.getBinary(dbi, 'key');
var zeroCopy = txn.getBinaryFast(dbi, 'key');
```

**Comment by Venemo** [comment] 2016-07-03 18:38
Yes, the issue should affect binaries as well. Although I believe currently there is something going on with regards the binaries. (I would need to review the code again, but I think the guy who ported it to nan v2 kind of forgot to make them zero-copy in the first place.)

Regarding your feedback about the ideas: I believe number 1 is the way to go. The performance loss would be basically the evaluation of an `if` statement. In addition to that, there could be a convenience function such as the one you suggest as well.

However, as a general usage pattern, I would suggest a longer lifespan for your transactions, ie. keep them open while you need those values. (Unless they would need to live _really_ long, in that case, of course copying the better way to go.)

**Comment by lukas-zech-software** [comment] 2016-07-04 07:25
I agree that the performance should always have the highest priority in LMDB, thats one of the main reasons we use it.
On of the reasons why LMDB is so fast ist because it relies on the the developer to handle it correctly and not having a lot of checks/error handling internally to avoid development errors.

If you read the LMDB mailing list most of Howard Chu's answers come down to 
> That's expected behaviour. Read the docs.

And for error handling, some of his tweets are quite enlightening:

> [Hint: if your code using LMDB crashes with a SEGV, you have a bug in your code. This is by design.] (https://twitter.com/hyc_symas/status/742515485846208512)

or

> [LMDB was aimed at correctness+efficiency first. Pretty is a non-goal. The rest followed.](https://twitter.com/hyc_symas/status/748113041800237056)

 

For me, the best way to deal with that would be a more detailed documentation and examples specifying this exact behaviour. I read the article about zero-copy in the README.md about 5 times without realizing that it would apply to my scenario as it only mentions cursors and **PUT** operations.
So for that would be  the first place to improve things.

As for changes it the code:

- Your idea number 1 would definitely make debugging a lot easier, especially for people not firm with the concepts of C and what zero-copy actually does. But it would also contradict with LMDB's idea of "performance before usability"

- The second idea would confront all developers with this behaviour way earlier and could force them to read the README more carefully to avoid this and further problems regarding zero-copy data.
Combined with an updated documentation this would be a good solution, forcing the devs to be more careful with LMDB 

- The third idea seemed quite good to me at first, but it contradicts a bit with the idea of a "clean" API. 
Such helper functions maybe useful, but also clutter the API and again, take responsibility of the developers. The code needed to copy  the data to a new memory block would be as simple as calling ```new Buffer()``` or ```Buffer.from()``` and can easily be every body them selves.
If you want to provide these helper functions in your library, it would at least not but them on the API itself, but have a __utils.js__ file  which can be required on its own and contains these helper functions as standalone static functions


So +1 for helping developers to help themselves instead of trying to do their own work 😄

**Comment by braydonf** [comment] 2016-07-04 16:29
> Yes, the issue should affect binaries as well. Although I believe currently there is something going on with regards the binaries. (I would need to review the code again, but I think the guy who ported it to nan v2 kind of forgot to make them zero-copy in the first place.)

Just took a look at it and it currently looks like `getBinary` and `getCurrentBinary` are using `valToBinary`, implemented as:

```cpp
return Nan::CopyBuffer((char*)data.mv_data, data.mv_size).ToLocalChecked();
```
From: https://github.com/Venemo/node-lmdb/blob/23a2bca022c121ee6368568e39b2beba7525c5fa/src/misc.cpp#L97-L104

Taking a look at the Nan documentation, and with `Nan::NewBuffer` states: 
> You must not free the memory space manually once you have created a Buffer in this way.
https://github.com/nodejs/nan/blob/master/doc/buffers.md#buffers

And indeed changing it to use `NewBuffer` will result in a similar segment fault as seen with `getCurrentString`:

```cpp
return Nan::NewBuffer((char*)data.mv_data, data.mv_size).ToLocalChecked();
```

**Comment by Venemo** [comment] 2016-07-19 12:57
I believe that @braydonf 's patch is a nice way forward, but I'm still pondering whether the zero-copy should be the default behaviour or not. In any case, it looks nice so far, but I'll review it further and let you know what I think.

**Comment by Venemo** [comment] 2017-03-19 11:43
I'm satisfied with the current API, so let's close this old issue.

**Closed by Venemo** 2017-03-19 11:43 UTC
Labels: task
