### ISSUE TITLE
Support for Node 12

### ISSUE THREAD

**Issue by kriszyp** [Venemo/node-lmdb#149] opened 2019-04-24 12:13 UTC
Add support for Node version 12, which I think is dependent on https://github.com/nodejs/nan/issues/849.

**Comment by josephg** [comment] 2019-05-23 03:21
Nan supports node 12. In that thread @bnoordhuis [says many issues are caused by old nan versions](https://github.com/nodejs/nan/issues/849#issuecomment-488292298)

**Comment by kriszyp** [comment] 2019-05-23 03:26
Yeah, this is fixed by #150, there is nothing wrong with Nan.

**Comment by innerop** [comment] 2019-05-30 18:36
Hi,

Thinking of trying this library. Is this still an open issue?

**Comment by Venemo** [comment] 2019-05-31 00:10
@innerop I've just merged the PR that addresses it. Will push a new release to NPM soon.

**Comment by Venemo** [comment] 2020-01-15 08:58
With the release of 0.8.0 on npm, I think this issue can be closed now.

**Closed by Venemo** 2020-01-15 08:58 UTC
